---
title: "Available topics in the introverse"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Available topics in the introverse}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
now <- lubridate::ymd(Sys.Date())
library(introverse)
```


> As of `r lubridate::stamp("March 1, 1999")(now)`, the following topics (organized by category) are available in the `{introverse}`. To get help for any topic, run `get_help("topic")`.

## Operators and Magrittr pipe

```{r operators}
show_topics("operators")
show_topics("magrittr")
```

<br>

## Base R 

_This category includes all functions that come with R, not only those in the "base" R package._

```{r base}
show_topics("base")
```

<br>

## `ggplot2` 

```{r ggplot2}
show_topics("ggplot2")
```

<br>

## `dplyr` 

```{r dplyr}
show_topics("dplyr")
```


<br>

## `tidyr` 

```{r tidyr}
show_topics("tidyr")
```


<br>

## `forcats` 

```{r forcats}
show_topics("forcats")
```


<br>

## `tibble` 

```{r tibble}
show_topics("tibble")
```
