---
title: "Get help online"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{get_help_online}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


### Get help with the example datasets

+ [**`carnivores`**](../introverse_docs/datasets_carnivores.html)
+ [**`msleep`**](../introverse_docs/datasets_msleep.html)

### Get help with operators and `magrittr` pipes

+ [**Assignment operators in `R`**](../introverse_docs/operators_assignment.html) 
+ [**Mathematical operators in `R`**](../introverse_docs/operators_mathematical.html) 
+ [**Logical operators in `R`**](../introverse_docs/operators_logical.html) 
+ [**`magrittr` pipe**](../introverse_docs/magrittr_pipe.html) 
+ [**`magrittr` assignment pipe**](../introverse_docs/magrittr_apipe.html) 

### Get help with Base `R` 

#### Working with data types

| Topic   |  Description  |
|----|----|
| [**`as.character()`**](../introverse_docs/base_as.character.html) | Coerce ("change") a value to be character type |
| [**`as.factor()`**](../introverse_docs/base_as.factor.html) | Coerce ("change") a value to be factor type|
| [**`as.numeric()`**](../introverse_docs/base_as.numeric.html) |Coerce ("change") a value to be character type |
| [**`class()`**](../introverse_docs/base_class.html) | Determine a value's type |


#### Working with R libraries/packages

| Function   |  Description  |
|----|----|
| [**`library()`**](../introverse_docs/base_library.html) | Load a library/package into an R session |
| [**`install.packages()`**](../introverse_docs/base_install.packages.html) | Install a library/package for the first time |

#### Working with files and directories

| Function   |  Description  |
|----|----|
| [**`getwd()`**](../introverse_docs/base_getwd.html) | Ask `R` what your R session's working directory is |
| [**`setwd()`**](../introverse_docs/base_setwd.html) | Change the current R session's working directory |
| [**`dir.exists()`**](../introverse_docs/base_file.exists.html) | Ask if a given directory (folder) exists on your computer |
| [**`file.exists()`**](../introverse_docs/base_file.exists.html) | Ask if a given file exists on your computer |
| [**`file.path()`**](../introverse_docs/base_file.path.html) | Construct a path to a given file or directory (folder) |

#### Working with numbers

| Function   |  Description  |
|----|----|
| [**`log()`**](../introverse_docs/base_log.html) | Calculate the natural log (or other specified base) of a number or array of numbers |
| [**`sqrt()`**](../introverse_docs/base_log.html) | Calculate the square root of a number or array of numbers |
| [**`abs()`**](../introverse_docs/base_abs.html) | Calculate the absolute value of a number or array of numbers |
| [**`round()`**](../introverse_docs/base_round.html) | Round a number or array of numbers to a specified number of decimal places |
| [**`ceiling()`**](../introverse_docs/base_ceiling.html) | Round a number or array of numbers up to the next highest integer |
| [**`floor()`**](../introverse_docs/base_ceiling.html) | Round a number or array of numbers down to the next lowest integer |

#### Working with arrays, strings, and more

| Function   |  Description  |
|----|----|
| [**`c()`**](../introverse_docs/base_c.html) | Create new arrays |
| [**`length()`**](../introverse_docs/base_length.html) | Determine the length of an array (_not_ of a single string) |
| [**`nchar()`**](../introverse_docs/base_nchar.html) | Determine the number of characters in a string |
| [**`levels()`**](../introverse_docs/base_levels.html) | Determine the levels (i.e., ordered categories) of a factor variable |
| [**`unique()`**](../introverse_docs/base_unique.html) | Remove duplicates from an array, i.e. keep only unique values |
| [**`paste()`** and **`paste0()`**](../introverse_docs/base_paste.html) | Combine several strings into one |
| [**`ifelse()`**](../introverse_docs/base_ifelse.html) | Assign a value based on whether a statement is `TRUE` or `FALSE` |
| [**`cat()`** and **`print`**](../introverse_docs/base_print.html) | Functions you can use to explicitly print |
| [**`all()`**](../introverse_docs/base_all.html) | Asks, "do ALL values in an array meet a logical condition?" |
| [**`any()`**](../introverse_docs/base_any.html) | Asks, "do ANY (at least one) values in an array meet a logical condition?" |



#### Working with data frames (and other objects)

| Function   |  Description  |
|----|----|
| [**`data.frame()`**](../introverse_docs/base_data.frame.html) | Create a new data frame from scratch |
| [**`nrow()`**](../introverse_docs/base_nrow.html) | Determine the number of rows in a tibble (data frame)  |
| [**`ncol()`**](../introverse_docs/base_nrow.html) | Determine the number of columns in a tibble (data frame)  |
| [**`names()`**](../introverse_docs/base_names.html) | Determine the column names of a tibble (data frame)  |
| [**`head()`**](../introverse_docs/base_head.html) | See the first 6 rows of a tibble (data frame) |
| [**`tail()`**](../introverse_docs/base_head.html) | See the last 6 rows of a tibble (data frame) |
| [**`summary()`**](../introverse_docs/base_summary.html) | See a summary of columns in tibble (data frame) |
| [**`str()`**](../introverse_docs/base_str.html) | See the structure of a tibble (data frame) |

#### Summary statistics

| Function   |  Description  |
|----|----|
| [**`mean()`**](../introverse_docs/base_mean.html) | Calculate the average of an array of numbers |
| [**`median()`**](../introverse_docs/base_mean.html) | Calculate the median of an array of numbers |
| [**`max()`**](../introverse_docs/base_mean.html) |  Calculate the maximum value of an array of numbers |
| [**`min()`**](../introverse_docs/base_mean.html) | Calculate the minimum value of an array of numbers |
| [**`sd()`**](../introverse_docs/base_mean.html) | Calculate the standard deviation of an array of numbers |
| [**`sum()`**](../introverse_docs/base_mean.html) |Calculate the sum of an array of numbers |
| [**`summary()`**](../introverse_docs/base_summary.html) | Calculate several summary statistics for an array of numbers |
| [**`table()`**](../introverse_docs/base_table.html) | Count the occurrences of each value in an array of any type  |



### Get help with `ggplot2`

#### Fundamental `ggplot2`

| Function   |  Description  |
|----|----|
| [**`aes()`**](../introverse_docs/ggplot2_aes.html) | Provide a `{ggplot2}` with aesthetic _mappings_ from dataset columns |
| [**`ggplot()`**](../introverse_docs/ggplot2_ggplot.html) | Tell `{ggplot2}` which dataset to plot and establish a `{ggplot2}` canvas |
| [**`ggsave()`**](../introverse_docs/ggplot2_ggsave.html) | Save a plot made with `{ggplot2}` to a file |


#### Geoms 

| Function   |  Description  |
|----|----|
| [**`geom_boxplot()`**](../introverse_docs/ggplot2_geom_boxplot.html) | Create boxplots |
| [**`geom_density()`**](../introverse_docs/ggplot2_geom_density.html) | Create density plots|
| [**`geom_histogram()`**](../introverse_docs/ggplot2_geom_histogram.html) | Create histograms |
| [**`geom_jitter()`**](../introverse_docs/ggplot2_geom_jitter.html) | Create jitter (strip) plots |
| [**`geom_point()`**](../introverse_docs/ggplot2_geom_point.html) | Create point shapes, often (but not always) to create scatterplots|
| [**`geom_smooth()`**](../introverse_docs/ggplot2_geom_smooth.html) | Add a trendline to a plot, often (but not always) to a scatterplot |
| [**`geom_col()`**](../introverse_docs/ggplot2_geom_col.html) | Create bar plots whose height corresponds to literal values in the data |
| [**`geom_bar()`**](../introverse_docs/ggplot2_geom_bar.html) |Create bar plots whose height corresponds to _counted number of observations_ of a categorical variable |
| [**`geom_text()`** and **`geom_label()`**](../introverse_docs/ggplot2_geom_text.html) | Create labels in plots |
| [**`geom_segment()`**](../introverse_docs/ggplot2_geom_segment.html) | Add line segments to plots |



#### Axes, labels, and faceting

| Function or tutorial   |  Description  |
|----|----|
| [**Axes tutorial**](https://sjspielman.github.io/introverse/articles/axes.html) | Customizing x- and y- axes
| [**`xlim()`**](../introverse_docs/ggplot2_xlim.html) | Change x-axis limits 
| [**`ylim()`**](../introverse_docs/ggplot2_xlim.html) | Change y-axis limits 
| [**`labs()`**](../introverse_docs/ggplot2_labs.html) | Customize plot labels, including axes, titles, and legends |
| [**`facet_wrap()`**](../introverse_docs/ggplot2_facet_wrap.html) | Create a faceted (paneled) plot across 1 variable
| [**`facet_grid()`**](../introverse_docs/ggplot2_facet_wrap.html) | Create a faceted (paneled) grid of plots across 2 variables



#### Color and fill scales

| Function or tutorial   |  Description  |
|----|----|
| [**Color and fill scales tutorial**](https://sjspielman.github.io/introverse/articles/color_fill_scales.html) | Customizing color and fill scales
| [**`scale_color_manual()`**](../introverse_docs/ggplot2_scale_color_manual.html) | Specify custom color scale mappings for discrete data
| [**`scale_fill_manual()`**](../introverse_docs/ggplot2_scale_color_manual.html) | Specify custom fill scale mappings for discrete data
| [**`scale_color_gradient()`**](../introverse_docs/ggplot2_scale_color_manual.html) | Specify custom color gradient scale mappings for continuous data
| [**`scale_fill_gradient()`**](../introverse_docs/ggplot2_scale_color_manual.html) | Specify custom fill gradient scale mappings for continuous data
| [**`scale_color_gradient2()`**](../introverse_docs/ggplot2_scale_color_manual.html) | Specify custom two-way color gradient scale mappings for continuous data
| [**`scale_fill_gradient2()`**](../introverse_docs/ggplot2_scale_color_manual.html) | Specify custom two-way fill gradient scale mappings for continuous data
| [**`scale_color_brewer()`**](../introverse_docs/ggplot2_scale_color_brewer.html) | Specify `colorbrewer` color scale mappings for discrete data
| [**`scale_fill_brewer()`**](../introverse_docs/ggplot2_scale_color_brewer.html) | Specify `colorbrewer` fill scale mappings for discrete data
| [**`scale_color_distiller()`**](../introverse_docs/ggplot2_scale_color_brewer.html) | Specify `colorbrewer` color scale mappings for continuous data
| [**`scale_fill_distiller()`**](../introverse_docs/ggplot2_scale_color_brewer.html) | Specify `colorbrewer` fill scale mappings for continuous data
| [**`scale_color_viridis_d()`**](../introverse_docs/ggplot2_scale_color_viridis_c.html) | Specify `viridis` color scale mappings for discrete data
| [**`scale_fill_viridis_d()`**](../introverse_docs/ggplot2_scale_color_viridis_c.html) | Specify `viridis` fill scale mappings for discrete data
| [**`scale_color_viridis_c()`**](../introverse_docs/ggplot2_scale_color_viridis_c.html) | Specify `viridis` color scale mappings for continuous data
| [**`scale_fill_viridis_c()`**](../introverse_docs/ggplot2_scale_color_viridis_c.html) | Specify `viridis` fill scale mappings for continuous data


#### Other scales

| Link   |  Description  |
|----|----|
| [**`scale_shape_manual()`**](../introverse_docs/ggplot2_scale_color_manual.html) | Specify custom shape mappings
| [**`scale_size_manual()`**](../introverse_docs/ggplot2_scale_color_manual.html) | Specify custom size mappings
| [**`scale_alpha_manual()`**](../introverse_docs/ggplot2_scale_color_manual.html) | Specify custom alpha (transparency) mappings
| [**`scale_linetype_manual()`**](../introverse_docs/ggplot2_scale_color_manual.html) | Specify custom linetype mappings


#### Themes

| Function   |  Description  |
|----|----|
| [**`theme()`** and associated tutoral](https://sjspielman.github.io/introverse/articles/themes.html) | Customizing themes
| [**`theme_set()`**](../introverse_docs/ggplot2_theme_set.html) | Set the default theme |
| [**`theme_gray()`**](../introverse_docs/ggplot2_theme_gray.html) | Specify the built-in "gray" (default) theme|
| [**`theme_grey()`**](../introverse_docs/ggplot2_theme_gray.html) | Specify the built-in "grey" (default) theme|
| [**`theme_bw()`**](../introverse_docs/ggplot2_theme_gray.html) | Specify the built-in "bw" theme|
| [**`theme_linedraw()`**](../introverse_docs/ggplot2_theme_gray.html) | Specify the built-in "linedraw" theme|
| [**`theme_light()`**](../introverse_docs/ggplot2_theme_gray.html) | Specify the built-in "light" theme|
| [**`theme_dark()`**](../introverse_docs/ggplot2_theme_gray.html) | Specify the built-in "dark" theme |
| [**`theme_minimal()`**](../introverse_docs/ggplot2_theme_gray.html) | Specify the built-in "minimal" theme|
| [**`theme_classic()`**](../introverse_docs/ggplot2_theme_gray.html) | Specify the "classic" theme |
| [**`theme_void()`**](../introverse_docs/ggplot2_theme_gray.html) | Specify the built-in "void" theme|


### Get help with `dplyr`


#### One-table verbs 

| Function   |  Description  |
|----|----|
| [**`arrange()`**](../introverse_docs/dplyr_arrange.html) | Arrange tibble (data frame) rows |
| [**`distinct()`**](../introverse_docs/dplyr_distinct.html) | Remove duplicate rows from a tibble (data frame) |
| [**`mutate()`**](../introverse_docs/dplyr_mutate.html) | Create new or modify existing columns in a tibble (data frame) |
| [**`filter()`**](../introverse_docs/dplyr_filter.html) | Keep only certain rows from a tibble (data frame) based on `TRUE` or `FALSE` |
| [**`select()`**](../introverse_docs/dplyr_select.html) | Keep, remove, or reorder columns in a tibble (data frame) |
| [**`rename()`**](../introverse_docs/dplyr_rename.html) | Rename existing columns in a tibble (data frame)|
| [**`glimpse()`**](../introverse_docs/dplyr_glimpse.html) | See an overview of tibble (data frame) contents |
| [**`pull()`**](../introverse_docs/dplyr_pull.html) | Extract out a column from a tibble (data frame) into its own array |
| [**`slice()`**](../introverse_docs/dplyr_slice.html) | Keep only certain rows from a tibble (data frame) based on index |
| [**`group_by()`**](../introverse_docs/dplyr_group_by.html) | Establish a grouping in a tibble (data frame) |
| [**`ungroup()`**](../introverse_docs/dplyr_group_by.html) | Undo any groupings in a tibble (data frame) |
| [**`summarize()`**](../introverse_docs/dplyr_summarize.html) | Summarize values in a tibble (data frame) to produce a smaller summarized tibble |
| [**`tally()`**](../introverse_docs/dplyr_tally.html) | Count the number of rows in each grouping of a tibble (data frame)|
| [**`count()`**](../introverse_docs/dplyr_count.html) | Simultaneously group and count the number of rows in each grouping of a tibble (data frame)|

#### Two-table verbs

| Function   |  Description  |
|----|----|
| [**`bind_cols()`**](../introverse_docs/dplyr_bind_cols.html) | Combine arrays or tibbles (data frames) by columns |
| [**`bind_rows()`**](../introverse_docs/dplyr_bind_cols.html) | Combine arrays or tibbles (data frames) by rows |
| [**`left_join()`**](../introverse_docs/dplyr_left_join.html) | Merge two relational tibbles (data frames) based on the left side |
| [**`right_join()`**](../introverse_docs/dplyr_right_join.html) | Merge two relational tibbles (data frames) based on the right side |
| [**`full_join()`**](../introverse_docs/dplyr_full_join.html) | Merge two relational tibbles (data frames) fully |
| [**`inner_join()`**](../introverse_docs/dplyr_inner_join.html) | Merge two relational tibbles (data frames) based on what they have in common |
| [**`anti_join()`**](../introverse_docs/dplyr_anti_join.html) | Merge relational tibbles (data frames) based on what they do not have in common |

#### Helper functions

| Function   |  Description  |
|----|----|
| [**`if_else()`**](../introverse_docs/dplyr_if_else.html) | Assign a value based on whether a statement is `TRUE` or `FALSE` , ensuring same type |
| [**`case_when()`**](../introverse_docs/dplyr_case_when.html) | Assign a value based on a series of conditions are `TRUE` or `FALSE` |
| [**`n()`**](../introverse_docs/dplyr_n.html) | Returns the number of rows in a tibble group |


### Get help with `tidyselect` helpers

| Function   |  Description  |
|----|----|
| [**`everything()`**](../introverse_docs/tidyselect_tidyselect.html)  | Select all columns, except those already explicitly stated |
| [**`contains()`**](../introverse_docs/tidyselect_tidyselect.html)    | Select all columns that contain a given string argument |
| [**`starts_with()`**](../introverse_docs/tidyselect_tidyselect.html)    | Select all columns that start with a given string, i.e. prefix |     
| [**`ends_with()`**](../introverse_docs/tidyselect_tidyselect.html)     | Select all columns that end with a given string, i.e. suffix | 
|  [**`last_col()`**](../introverse_docs/tidyselect_tidyselect.html)  | Select the last column |
| [**`matches()`**](../introverse_docs/tidyselect_tidyselect.html)      | Select all columns that match a regular expression (a special type of pattern-matching string) |


### Get help with `forcats`

| Function   |  Description  |
|----|----|
| [**`fct_relevel()`**](../introverse_docs/forcats_fct_relevel.html) | Reorder levels in a factor to a custom order |
| [**`fct_infreq()`**](../introverse_docs/forcats_fct_infreq.html) | Reorder levels factor in a factor based on frequency |
| [**`fct_rev()`**](../introverse_docs/forcats_fct_rev.html) | Reverse the order of levels in a factor |
| [**`fct_reorder()`**](../introverse_docs/forcats_fct_reorder.html) | Reorder levels in a factor based on values of another variable |
| [**`fct_lump_n()`**](../introverse_docs/forcats_fct_lump_n.html) | Combine infrequently occurring levels of a factor into one |
| [**`fct_lump_min()`**](../introverse_docs/forcats_fct_lump_n.html) | Combine infrequently occurring levels of a factor into one |
| [**`fct_lump_prop()`**](../introverse_docs/forcats_fct_lump_n.html) | Combine infrequently occurring levels of a factor into one |


### Get help with `readr`

| Function   |  Description  |
|----|----|
| [**`read_csv()`**](../introverse_docs/readr_read_csv.html)  |  Read a CSV file into `R` |
| [**`read_tsv()`**](../introverse_docs/readr_read_csv.html)  |  Read a TSV file into `R` |
| [**`read_csv2()`**](../introverse_docs/readr_read_csv.html)  |  Read a CSV2 file into `R` |
| [**`read_delim()`**](../introverse_docs/readr_read_csv.html)  |  Read a delimited file of any kind into `R` |
| [**`write_csv()`**](../introverse_docs/readr_write_csv.html)  |  Write (save) a tibble (data frame) to a CSV file |
| [**`write_tsv()`**](../introverse_docs/readr_write_csv.html)  | Write (save) a tibble (data frame) to a TSV file |
| [**`write_csv2()`**](../introverse_docs/readr_write_csv.html)  |  Write (save) a tibble (data frame) to a CSV2 file |
| [**`write_delim()`**](../introverse_docs/readr_write_csv.html)  | Write (save) a tibble (data frame) to a delimited file |



### Get help with `tibble`

| Function   |  Description  |
|----|----|
| [**`as_tibble()`**](../introverse_docs/tibble_as_tibble.html) | Coerce a variable (often a data frame) into a tibble |
| [**`tibble()`**](../introverse_docs/tibble_tibble.html) | Create a new tibble from scratch |
| [**`tribble()`**](../introverse_docs/tibble_tibble.html) | Create a new tibble from scratch |


### Get help with `tidyr`

| Function   |  Description  |
|----|----|
| [**`pivot_longer()`**](../introverse_docs/tidyr_pivot_longer.html)  |  Make a tibble (data frame) longer |
| [**`pivot_wider()`**](../introverse_docs/tidyr_pivot_wider.html) | Make a tibble (data frame) wider |
| [**`drop_na()`**](../introverse_docs/tidyr_drop_na.html) | Remove rows containing `NA` values from a tibble (data frame) |
| [**`unite()`**](../introverse_docs/tidyr_unite.html) | Unite (combine) two columns in a tibble (data frame) into a single column |
| [**`separate()`**](../introverse_docs/tidyr_separate.html) | Separate a single column in a tibble (data frame) into two new columns |


### Get help with `stringr`

| Function   |  Description  |
|----|----|
| [**`str_count()`**](../introverse_docs/stringr_str_count.html)  |  Count the number of occurrences of a substring or regular expression in a string |
| [**`str_replace()`**](../introverse_docs/stringr_str_replace.html) | Replace _the first_ occurrence of a substring or regular expression in a string with a given replacement string |
| [**`str_replace_all()`**](../introverse_docs/stringr_str_replace.html) | Replace _all_ occurrences of a substring or regular expression in a string with a given replacement string |
| [**`str_detect()`**](../introverse_docs/stringr_str_detect.html) |  Determine whether it is `TRUE` or `FALSE` that a given string contains a substring |
| [**`str_starts()`**](../introverse_docs/stringr_str_starts.html) | Determine whether it is `TRUE` or `FALSE` that a given string starts with a given substring  |
| [**`str_ends()`**](../introverse_docs/stringr_str_starts.html) | Determine whether it is `TRUE` or `FALSE` that a given string ends with a given substring |


### Get help with `glue`

| Function   |  Description  |
|----|----|
| [**`glue()`**](../introverse_docs/glue_glue.html)  |  Quickly combine strings and variables into a single string |