---
title: "`log()`"
author: "{introverse} quick docs"
output: 
  html_document:
    highlight: pygments
    theme: flatly
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE)
```


## Description

The `log()` function comes with R and is part of the Base R `{base}` package.
  
We use this function to calculate the log of a number or numeric array. By default, the function calculates the natural log (base `e`). Provide a second argument to change the base.




## Conceptual usage 

```{r usage, eval=FALSE}
log(number to get the natural log of)

log(number to get the base x log of, x)

log(numeric array to get natural log of all its values)
```

## Examples


```{r example1}
# Find the natural log of 107
log(107)
```

<br>  <!-- Do not delete the <br>, and make sure to keep the previous and following lines blank. -->

```{r example2}
# Find the natural log of a defined variable
x <- 107
log(x)
```

<br>  <!-- Do not delete the <br>, and make sure to keep the previous and following lines blank. -->


```{r example3}
# Find the log of 107 in base 5
log(107, 5)
```

<br>  <!-- Do not delete the <br>, and make sure to keep the previous and following lines blank. -->


```{r example4}
# Find the natural log of all values in an array
log( c(100, 110, 120) )
```

<br>  <!-- Do not delete the <br>, and make sure to keep the previous and following lines blank. -->


```{r example5}
# Find the log in base 2 of all values in an array
my_array <- c(100, 110, 120)
log( my_array, 2 )
```
