---
title: "`dplyr::glimpse()`"
author: "{introverse} quick docs"
output: 
  html_document:
    highlight: pygments
    theme: flatly
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE)
library(dplyr)
```


## Description

The [`glimpse()`](https://dplyr.tidyverse.org/reference/glimpse.html) function is part of the [`{dplyr}`](https://dplyr.tidyverse.org/) package, which is part of the [`{tidyverse}`](https://www.tidyverse.org/).

It is used to view a content overview of a tibble (data frame).


<!-- Add the following if the topic is a function that does NOT come with base R, and uncomment/fill in the subsequent multiline HTML comment: -->
To use this function, you need to either first load the `{dplyr}` library, or always use the function with `dplyr::glimpse()` notation.

```{r description, eval=FALSE}
# Load the library
library(dplyr)
# Or, load the full tidyverse:
library(tidyverse)

# Or, use :: notation
dplyr::glimpse()
```


## Conceptual usage 

```{r usage, eval=FALSE}
glimpse(tibble)
```

## Examples

> Run `get_help("msleep")` for a refresher on the `msleep` dataset.

```{r example1}
# Glimpse the msleep dataset
glimpse(msleep)
```
